import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";
import { ToastContainer } from "react-toastify";

const OpenSans = localFont({
  src: "./fonts/OpenSans-VariableFont_wdth,wght.ttf",
  variable: "--font-open-sans",
  weight: "400, 500, 600, 700",
});

export const metadata: Metadata = {
  title: "Luminor",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${OpenSans.variable} font-openSans  antialiased text-textColor-primary`}
      >
        <ReduxProvider>
          {children}
        </ReduxProvider>
        <ToastContainer position="top-right" />
      </body>
    </html>
  );
}
